/* Batch invoicing constants */
export const BATCH_HISTORY_PROCESSING = 'BATCH_HISTORY_PROCESSING';
export const BATCH_HISTORY_FINALIZED = 'BATCH_HISTORY_FINALIZED';
export const BATCH_HISTORY_ENDED_WITH_ERRORS = 'BATCH_HISTORY_ENDED_WITH_ERRORS';

export const ECONOMIC_ACTIVITY_ACTIVE = 'ECONOMIC_ACTIVITY_ACTIVE';
export const ECONOMIC_ACTIVITY_LOCK = 'ECONOMIC_ACTIVITY_LOCK';
